# Generated by Django 3.2.6 on 2021-08-13 15:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210812_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Дочерняя категория')),
                ('to_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Отношение категорий',
                'verbose_name_plural': 'Отношения категорий',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='parents',
        ),
        migrations.AddField(
            model_name='category',
            name='parents',
            field=models.ManyToManyField(blank=True, through='core.CategoryParent', to='core.Category', verbose_name='Родительские категории'),
        ),
        migrations.AddConstraint(
            model_name='categoryparent',
            constraint=models.UniqueConstraint(fields=('from_category', 'to_category'), name='unique_category_parent'),
        ),
        migrations.AddConstraint(
            model_name='categoryparent',
            constraint=models.CheckConstraint(check=models.Q(('from_category', django.db.models.expressions.F('to_category')), _negated=True), name='self_parent_category_check'),
        ),
    ]
