# Generated by Django 3.2.6 on 2021-08-16 14:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20210814_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фото продукта', 'verbose_name_plural': 'Фото продукта'},
        ),
        migrations.AddField(
            model_name='shop',
            name='product_managers',
            field=models.ManyToManyField(limit_choices_to=models.Q(('groups__name', 'product managers')), related_name='managed_shops', to=settings.AUTH_USER_MODEL, verbose_name='Менеджеры продуктов'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Цена'),
        ),
    ]
